// Package catalog resolves the model tier table the kernel's grid search
// will use in Phase 2+. PLAN.md §4 originally proposed a self-updating
// fetch from the Anthropic models API; that source does not exist in the
// Claude Code hook environment (no API key, and /v1/models carries no
// pricing field regardless -- docs/verified.md V7). Instead: a compiled-in
// table regenerated by scripts/gen-catalog.go against the public pricing
// docs, overridable wholesale by ~/.deadeye/catalog.json.
package catalog

import (
	"encoding/json"
	"os"

	"github.com/deepaksinghcs14/deadeye-cc/internal/meta"
)

// Model is one catalog entry. Prices are USD per million tokens.
type Model struct {
	ID          string  `json:"model_id"`
	Family      string  `json:"family"`
	InputPrice  float64 `json:"input_price"`
	OutputPrice float64 `json:"output_price"`
	Tier        int     `json:"tier"` // 0 = cheapest, ascending
}

type Catalog struct {
	Models  []Model `json:"models"`
	BuiltAt string  `json:"built_at"`
	Source  string  `json:"source"` // "builtin" | "override"
}

// Load returns ~/.deadeye/catalog.json if present and non-empty, else the
// compiled-in table. No network call is made.
func Load() Catalog {
	if b, err := os.ReadFile(meta.CatalogOverridePath()); err == nil {
		var c Catalog
		if json.Unmarshal(b, &c) == nil && len(c.Models) > 0 {
			c.Source = "override"
			return c
		}
	}
	return builtin
}

// TierFor returns a model's tier by id, and whether it was found.
func (c Catalog) TierFor(id string) (int, bool) {
	for _, m := range c.Models {
		if m.ID == id {
			return m.Tier, true
		}
	}
	return 0, false
}

// Cheapest returns the lowest-tier model in the catalog.
func (c Catalog) Cheapest() (Model, bool) {
	if len(c.Models) == 0 {
		return Model{}, false
	}
	cheapest := c.Models[0]
	for _, m := range c.Models[1:] {
		if m.Tier < cheapest.Tier {
			cheapest = m
		}
	}
	return cheapest, true
}
