// Package catalog resolves the model tier table the kernel's grid search
// will use in Phase 2+. PLAN.md §4 originally proposed a self-updating
// fetch from the Anthropic models API; that source does not exist in the
// Claude Code hook environment (no API key, and /v1/models carries no
// pricing field regardless -- docs/verified.md V7). Instead: a compiled-in
// table regenerated by scripts/gen-catalog.go against the public pricing
// docs, overridable wholesale by ~/.deadeye/catalog.json.
package catalog

import (
	"encoding/json"
	"os"

	"github.com/deepaksinghcs14/deadeye-cc/internal/meta"
)

// Model is one catalog entry. Prices are USD per million tokens.
type Model struct {
	ID          string  `json:"model_id"`
	Family      string  `json:"family"`
	InputPrice  float64 `json:"input_price"`
	OutputPrice float64 `json:"output_price"`
	Tier        int     `json:"tier"`           // 0 = cheapest, ascending
	Role        string  `json:"role,omitempty"` // "" | RoleUnsureCeiling | RoleHighCeiling
}

// The two roles the kernel's ceilings resolve by preference, over raw tier
// numbers -- see UnsureCeiling/HighCeiling. At most one model should carry
// each; TestBuiltinHasExactlyOneOfEachCeilingRole guards the compiled-in
// table.
const (
	RoleUnsureCeiling = "unsure_ceiling"
	RoleHighCeiling   = "high_ceiling"
)

type Catalog struct {
	Models  []Model `json:"models"`
	BuiltAt string  `json:"built_at"`
	Source  string  `json:"source"` // "builtin" | "override" | "remote"
}

// Load returns, in order: ~/.deadeye/catalog.json (a user's explicit
// override, any shape they wrote -- never validated beyond "has models",
// per INV-5 fail-open), else ~/.deadeye/catalog-cache.json (the
// background-refreshed hosted copy, only if it passes Valid() and isn't
// older than the compiled-in table), else the compiled-in table. No
// network call is made here -- the cache file is written by
// cmd/deadeye's catalogcheck.go, never by Load itself.
func Load() Catalog {
	if b, err := os.ReadFile(meta.CatalogOverridePath()); err == nil {
		var c Catalog
		if json.Unmarshal(b, &c) == nil && len(c.Models) > 0 {
			c.Source = "override"
			return c
		}
	}
	if b, err := os.ReadFile(meta.CatalogCachePath()); err == nil {
		var c Catalog
		if json.Unmarshal(b, &c) == nil && c.Valid() && c.BuiltAt >= builtin.BuiltAt {
			c.Source = "remote"
			return c
		}
	}
	return builtin
}

// Valid reports whether a fetched catalog is safe to route on. Applied
// only to the remote cache (Load's override path stays deliberately
// lenient) -- a bad publish must degrade to the builtin, never half-apply.
func (c Catalog) Valid() bool {
	if len(c.Models) < 2 {
		return false
	}
	seenTier := make(map[int]bool, len(c.Models))
	seenRole := make(map[string]bool, 2)
	hasTierZero := false
	for _, m := range c.Models {
		if m.ID == "" || m.Family == "" {
			return false
		}
		if m.InputPrice <= 0 || m.OutputPrice <= 0 {
			return false
		}
		if m.Tier < 0 || seenTier[m.Tier] {
			return false
		}
		seenTier[m.Tier] = true
		hasTierZero = hasTierZero || m.Tier == 0
		switch m.Role {
		case "":
		case RoleUnsureCeiling, RoleHighCeiling:
			if seenRole[m.Role] {
				return false
			}
			seenRole[m.Role] = true
		default:
			return false
		}
	}
	if !hasTierZero {
		return false
	}
	unsure, hasUnsure := c.modelWithRole(RoleUnsureCeiling)
	high, hasHigh := c.modelWithRole(RoleHighCeiling)
	if hasUnsure && hasHigh && high.Tier < unsure.Tier {
		return false
	}
	return true
}

// TierFor returns a model's tier by id, and whether it was found.
func (c Catalog) TierFor(id string) (int, bool) {
	for _, m := range c.Models {
		if m.ID == id {
			return m.Tier, true
		}
	}
	return 0, false
}

// FamilyFor returns a model's family alias by id (e.g. "haiku"), and
// whether it was found. The Agent tool's model parameter accepts only the
// short family alias (sonnet|opus|haiku|fable), not a full model id --
// confirmed from the tool's own schema -- so routing enforcement rewrites
// to Family, not ID.
func (c Catalog) FamilyFor(id string) (string, bool) {
	for _, m := range c.Models {
		if m.ID == id {
			return m.Family, true
		}
	}
	return "", false
}

// ModelAtTier returns the model id at the given tier, and whether one exists.
func (c Catalog) ModelAtTier(tier int) (string, bool) {
	for _, m := range c.Models {
		if m.Tier == tier {
			return m.ID, true
		}
	}
	return "", false
}

// Cheapest returns the lowest-tier model in the catalog.
func (c Catalog) Cheapest() (Model, bool) {
	if len(c.Models) == 0 {
		return Model{}, false
	}
	cheapest := c.Models[0]
	for _, m := range c.Models[1:] {
		if m.Tier < cheapest.Tier {
			cheapest = m
		}
	}
	return cheapest, true
}

// UnsureCeiling and HighCeiling resolve the model each of the kernel's two
// ceilings should route to: the catalog's explicit role tag if present --
// the forward-compatible path, since promoting a new model to either role
// is then a data edit, not a kernel.go code change -- else the historical
// fixed tier number (1 and 2 respectively) this kernel has always used.
// The fallback matters: it means a catalog written before Role existed
// (any pre-existing ~/.deadeye/catalog.json override, or a hand-built test
// catalog with plain Tier ints) resolves identically to today, unchanged.
//
// The fallback is deliberately NOT "the catalog's most expensive tier" --
// that was a real bug (kernel.go's own history: thin evidence once routed
// to the priciest model simply for being priciest). A ceiling is either a
// human's explicit role tag, or a fixed number known in advance to be
// reasonable -- never inferred from "whatever the catalog happens to rank
// highest today."
func (c Catalog) UnsureCeiling() (Model, bool) {
	if m, ok := c.modelWithRole(RoleUnsureCeiling); ok {
		return m, true
	}
	return c.modelAtOrBelowTier(1)
}

func (c Catalog) HighCeiling() (Model, bool) {
	if m, ok := c.modelWithRole(RoleHighCeiling); ok {
		return m, true
	}
	return c.modelAtOrBelowTier(2)
}

func (c Catalog) modelWithRole(role string) (Model, bool) {
	for _, m := range c.Models {
		if m.Role == role {
			return m, true
		}
	}
	return Model{}, false
}

// modelAtOrBelowTier returns the highest-tier model at or under maxTier --
// the pre-Role ceiling-selection scan, kept verbatim as the fallback.
func (c Catalog) modelAtOrBelowTier(maxTier int) (Model, bool) {
	best := -1
	var bestModel Model
	for _, m := range c.Models {
		if m.Tier <= maxTier && m.Tier > best {
			best = m.Tier
			bestModel = m
		}
	}
	return bestModel, best != -1
}
