//go:build ignore

// gen-catalog regenerates internal/catalog/catalog_gen.go from the price
// seed table below, ranked by blended price (input + 4*output, a rough
// usage-mix weight per PLAN.md §4). Run after editing seed prices, or once
// per release to pick up new models:
//
//	go run scripts/gen-catalog.go
//
// There is no reachable pricing API from the Claude Code hook environment
// (docs/verified.md V7), so the seed table below is maintained by hand
// against https://platform.claude.com/docs/en/about-claude/pricing.
package main

import (
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type seedModel struct {
	id, family              string
	inputPrice, outputPrice float64
}

// Seed prices, USD per million tokens. Update these, not catalog_gen.go.
var seed = []seedModel{
	{"claude-haiku-4-5-20251001", "haiku", 1, 5},
	{"claude-sonnet-5", "sonnet", 2, 10},
	{"claude-opus-5", "opus", 5, 25},
	{"claude-fable-5", "fable", 10, 50},
}

const builtAt = "2026-08-02" // date the seed prices above were fetched
const sourceURL = "https://platform.claude.com/docs/en/about-claude/pricing"

func blended(m seedModel) float64 { return m.inputPrice + 4*m.outputPrice }

func main() {
	ranked := append([]seedModel(nil), seed...)
	sort.SliceStable(ranked, func(i, j int) bool { return blended(ranked[i]) < blended(ranked[j]) })

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by scripts/gen-catalog.go from a manually-maintained price
// seed table; DO NOT EDIT directly -- edit the seed in the generator and
// re-run `+"`go run ./scripts/gen-catalog.go`"+`.
//
// Prices sourced from %s,
// fetched %s. No reachable pricing API exists in the Claude Code
// hook environment (docs/verified.md V7), so this table has no automated
// refresh; ~/.deadeye/catalog.json overrides it entirely if present.
package catalog

var builtin = Catalog{
	BuiltAt: %q,
	Source:  "builtin",
	Models: []Model{
`, sourceURL, builtAt, builtAt)

	for tier, m := range ranked {
		fmt.Fprintf(&b, "\t\t{ID: %q, Family: %q, InputPrice: %v, OutputPrice: %v, Tier: %d},\n",
			m.id, m.family, m.inputPrice, m.outputPrice, tier)
	}
	b.WriteString("\t},\n}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-catalog: format:", err)
		os.Exit(1)
	}
	if err := os.WriteFile("internal/catalog/catalog_gen.go", out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gen-catalog: write:", err)
		os.Exit(1)
	}
	fmt.Println("wrote internal/catalog/catalog_gen.go")
}
