//go:build ignore

// gen-catalog regenerates internal/catalog/catalog_gen.go from the price
// seed table below, ranked by blended price (input + 4*output, a rough
// usage-mix weight per PLAN.md §4). Run after editing seed prices, or once
// per release to pick up new models:
//
//	go run scripts/gen-catalog.go
//
// There is no reachable pricing API from the Claude Code hook environment
// (docs/verified.md V7), so the seed table below is maintained by hand
// against https://platform.claude.com/docs/en/about-claude/pricing.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type seedModel struct {
	id, family              string
	inputPrice, outputPrice float64
	role                    string // "" | "unsure_ceiling" | "high_ceiling" -- see catalog.Role*
}

// Seed prices, USD per million tokens. Update these, not catalog_gen.go.
//
// role marks which model the kernel's two ceilings resolve to (see
// catalog.Catalog.UnsureCeiling/HighCeiling) -- exactly one model should
// carry "unsure_ceiling" and one "high_ceiling"
// (TestBuiltinHasExactlyOneOfEachCeilingRole guards this). fable stays
// un-roled deliberately: it's not reachable by automatic routing, on
// purpose, the same real-world outcome as before Role existed -- now an
// explicit choice here instead of an emergent side effect of a tier
// number hardcoded in kernel.go.
var seed = []seedModel{
	{"claude-haiku-4-5-20251001", "haiku", 1, 5, ""},
	{"claude-sonnet-5", "sonnet", 2, 10, "unsure_ceiling"},
	{"claude-opus-5", "opus", 5, 25, "high_ceiling"},
	{"claude-fable-5", "fable", 10, 50, ""},
}

const builtAt = "2026-08-02" // date the seed prices above were fetched
const sourceURL = "https://platform.claude.com/docs/en/about-claude/pricing"

func blended(m seedModel) float64 { return m.inputPrice + 4*m.outputPrice }

func main() {
	ranked := append([]seedModel(nil), seed...)
	sort.SliceStable(ranked, func(i, j int) bool { return blended(ranked[i]) < blended(ranked[j]) })

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by scripts/gen-catalog.go from a manually-maintained price
// seed table; DO NOT EDIT directly -- edit the seed in the generator and
// re-run `+"`go run ./scripts/gen-catalog.go`"+`.
//
// Prices sourced from %s,
// fetched %s. No reachable pricing API exists in the Claude Code
// hook environment (docs/verified.md V7), so this table has no automated
// refresh; ~/.deadeye/catalog.json overrides it entirely if present.
package catalog

var builtin = Catalog{
	BuiltAt: %q,
	Source:  "builtin",
	Models: []Model{
`, sourceURL, builtAt, builtAt)

	for tier, m := range ranked {
		if m.role != "" {
			fmt.Fprintf(&b, "\t\t{ID: %q, Family: %q, InputPrice: %v, OutputPrice: %v, Tier: %d, Role: %q},\n",
				m.id, m.family, m.inputPrice, m.outputPrice, tier, m.role)
			continue
		}
		fmt.Fprintf(&b, "\t\t{ID: %q, Family: %q, InputPrice: %v, OutputPrice: %v, Tier: %d},\n",
			m.id, m.family, m.inputPrice, m.outputPrice, tier)
	}
	b.WriteString("\t},\n}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-catalog: format:", err)
		os.Exit(1)
	}
	if err := os.WriteFile("internal/catalog/catalog_gen.go", out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gen-catalog: write:", err)
		os.Exit(1)
	}
	fmt.Println("wrote internal/catalog/catalog_gen.go")

	if err := writeHostedCatalog(ranked); err != nil {
		fmt.Fprintln(os.Stderr, "gen-catalog: hosted json:", err)
		os.Exit(1)
	}
	fmt.Println("wrote docs/site/catalog.json")
}

// hostedModel/hostedCatalog mirror internal/catalog.Model/Catalog's JSON
// shape exactly (kept as a local copy, not an import, since this file is
// //go:build ignore and runs outside the module's normal build).
type hostedModel struct {
	ID          string  `json:"model_id"`
	Family      string  `json:"family"`
	InputPrice  float64 `json:"input_price"`
	OutputPrice float64 `json:"output_price"`
	Tier        int     `json:"tier"`
	Role        string  `json:"role,omitempty"`
}

type hostedCatalog struct {
	Models  []hostedModel `json:"models"`
	BuiltAt string        `json:"built_at"`
	Source  string        `json:"source"`
}

// writeHostedCatalog publishes docs/site/catalog.json -- the file
// cmd/deadeye/catalogcheck.go's background refresh fetches from GitHub
// Pages. Pretty-printed deliberately: this file is meant to be hand-edited
// directly for a fast model/price change (edit, commit, push -- no
// release), so it should read like a table, not a minified blob. A hand
// edit here must be brought back into the seed above before the next
// `go run` clobbers it.
func writeHostedCatalog(ranked []seedModel) error {
	hc := hostedCatalog{BuiltAt: builtAt, Source: "hosted"}
	for tier, m := range ranked {
		hc.Models = append(hc.Models, hostedModel{
			ID: m.id, Family: m.family, InputPrice: m.inputPrice, OutputPrice: m.outputPrice,
			Tier: tier, Role: m.role,
		})
	}
	b, err := json.MarshalIndent(hc, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile("docs/site/catalog.json", append(b, '\n'), 0o644)
}
